package cn.junang.sys.model;

import java.util.Date;

public class SysLoginLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_login_log.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_login_log.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_login_log.login_time
     *
     * @mbg.generated
     */
    private Date loginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_login_log.location
     *
     * @mbg.generated
     */
    private String location;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_login_log.ip
     *
     * @mbg.generated
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_login_log.user_system
     *
     * @mbg.generated
     */
    private String userSystem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_login_log.user_browser
     *
     * @mbg.generated
     */
    private String userBrowser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login_log.id
     *
     * @return the value of sys_login_log.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login_log.id
     *
     * @param id the value for sys_login_log.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login_log.username
     *
     * @return the value of sys_login_log.username
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login_log.username
     *
     * @param username the value for sys_login_log.username
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login_log.login_time
     *
     * @return the value of sys_login_log.login_time
     *
     * @mbg.generated
     */
    public Date getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login_log.login_time
     *
     * @param loginTime the value for sys_login_log.login_time
     *
     * @mbg.generated
     */
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login_log.location
     *
     * @return the value of sys_login_log.location
     *
     * @mbg.generated
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login_log.location
     *
     * @param location the value for sys_login_log.location
     *
     * @mbg.generated
     */
    public void setLocation(String location) {
        this.location = location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login_log.ip
     *
     * @return the value of sys_login_log.ip
     *
     * @mbg.generated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login_log.ip
     *
     * @param ip the value for sys_login_log.ip
     *
     * @mbg.generated
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login_log.user_system
     *
     * @return the value of sys_login_log.user_system
     *
     * @mbg.generated
     */
    public String getUserSystem() {
        return userSystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login_log.user_system
     *
     * @param userSystem the value for sys_login_log.user_system
     *
     * @mbg.generated
     */
    public void setUserSystem(String userSystem) {
        this.userSystem = userSystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login_log.user_browser
     *
     * @return the value of sys_login_log.user_browser
     *
     * @mbg.generated
     */
    public String getUserBrowser() {
        return userBrowser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login_log.user_browser
     *
     * @param userBrowser the value for sys_login_log.user_browser
     *
     * @mbg.generated
     */
    public void setUserBrowser(String userBrowser) {
        this.userBrowser = userBrowser;
    }
}
