package cn.alibab.sys.model;

public class SysResources {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.pid
     *
     * @mbg.generated
     */
    private Long pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.perms
     *
     * @mbg.generated
     */
    private String perms;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.icon
     *
     * @mbg.generated
     */
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.ismenu
     *
     * @mbg.generated
     */
    private Boolean ismenu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.sn
     *
     * @mbg.generated
     */
    private Long sn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.isopen
     *
     * @mbg.generated
     */
    private Boolean isopen;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.id
     *
     * @return the value of sys_resources.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.id
     *
     * @param id the value for sys_resources.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.pid
     *
     * @return the value of sys_resources.pid
     *
     * @mbg.generated
     */
    public Long getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.pid
     *
     * @param pid the value for sys_resources.pid
     *
     * @mbg.generated
     */
    public void setPid(Long pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.name
     *
     * @return the value of sys_resources.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.name
     *
     * @param name the value for sys_resources.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.url
     *
     * @return the value of sys_resources.url
     *
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.url
     *
     * @param url the value for sys_resources.url
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.perms
     *
     * @return the value of sys_resources.perms
     *
     * @mbg.generated
     */
    public String getPerms() {
        return perms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.perms
     *
     * @param perms the value for sys_resources.perms
     *
     * @mbg.generated
     */
    public void setPerms(String perms) {
        this.perms = perms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.icon
     *
     * @return the value of sys_resources.icon
     *
     * @mbg.generated
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.icon
     *
     * @param icon the value for sys_resources.icon
     *
     * @mbg.generated
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.ismenu
     *
     * @return the value of sys_resources.ismenu
     *
     * @mbg.generated
     */
    public Boolean getIsmenu() {
        return ismenu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.ismenu
     *
     * @param ismenu the value for sys_resources.ismenu
     *
     * @mbg.generated
     */
    public void setIsmenu(Boolean ismenu) {
        this.ismenu = ismenu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.sn
     *
     * @return the value of sys_resources.sn
     *
     * @mbg.generated
     */
    public Long getSn() {
        return sn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.sn
     *
     * @param sn the value for sys_resources.sn
     *
     * @mbg.generated
     */
    public void setSn(Long sn) {
        this.sn = sn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.isopen
     *
     * @return the value of sys_resources.isopen
     *
     * @mbg.generated
     */
    public Boolean getIsopen() {
        return isopen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.isopen
     *
     * @param isopen the value for sys_resources.isopen
     *
     * @mbg.generated
     */
    public void setIsopen(Boolean isopen) {
        this.isopen = isopen;
    }
}