package cn.alibab.sys.model;

public class SysRoleResources {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_resources.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_resources.role_id
     *
     * @mbg.generated
     */
    private Long roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_resources.res_id
     *
     * @mbg.generated
     */
    private Long resId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_resources.id
     *
     * @return the value of sys_role_resources.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_resources.id
     *
     * @param id the value for sys_role_resources.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_resources.role_id
     *
     * @return the value of sys_role_resources.role_id
     *
     * @mbg.generated
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_resources.role_id
     *
     * @param roleId the value for sys_role_resources.role_id
     *
     * @mbg.generated
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_resources.res_id
     *
     * @return the value of sys_role_resources.res_id
     *
     * @mbg.generated
     */
    public Long getResId() {
        return resId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_resources.res_id
     *
     * @param resId the value for sys_role_resources.res_id
     *
     * @mbg.generated
     */
    public void setResId(Long resId) {
        this.resId = resId;
    }
}